database:
  host: "localhost"
  port: "3306"
  username: "your_username"
  db_name: "your_database"
  password: "your_password"

debug: false

bungeecord:
  use: false # ğŸ”„ True = pÅ™epojÃ­ na jinÃ½ server, False = teleportuje na end_location
  hub_server: "hub" # ğŸ¯ Server, kam se hrÃ¡Äi pÅ™epojÃ­, pokud je aktivnÃ­ BungeeCord

game:
  required_player_percentage: 50.0  # âœ… PoÅ¾adovanÃ© % hrÃ¡ÄÅ¯ z maximÃ¡lnÃ­ho poÄtu (napÅ™. 50 %)
  item_spawn_interval: 3 # In seconds
  celebration_time: 5 # Celebration in seconds